extends: jpeg576_fusion_local_weighted_val_wavelet.yaml
paths:
  run_name: jpeg576_wavelet_dual_b0
model:
  encoder_name: pvt_v2_b0
  noise_encoder_name: pvt_v2_b0
  guided_radius: 2
  guided_epsilon: 0.01
  guided_scale: 0.25
  dual_fusion_width: 16
